version: '3.8'
services:
  csvserver:
    image: infracloudio/csvserver
    ports:
      - "127.0.0.1:9393:9300"
    volumes:
      - /home/rana/Desktop/csvserver/solution/inputFile:/csvserver/inputdata
    env_file:
      - csvserver.env

  prometheus:
    image: prom/prometheus:v2.22.0
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - /home/rana/Desktop/csvserver/solution/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
