version: '3.8'
services:
  csvserver:
    image: infracloudio/csvserver
    ports:
      - "127.0.0.1:9393:9300"
    volumes:
      - /home/rana/Desktop/csvserver/solution/inputFile:/csvserver/inputdata
    env_file:
      - csvserver.env
